name: Create Pull Request to Push Dev to Release

on:
  pull_request:
  push:
    branches:
    - develop
    - release

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Check out release
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: release
    - name: Install hub
      run: |
        sudo apt install hub
    - name: Reset release branch to base on develop
      run: |
        hub checkout -b merge-develop-to-release
        hub fetch origin develop:develop
        hub reset --hard develop
    - name: Create Pull Request
      run: |
        hub push -u origin merge-develop-to-release
        hub pull-request -m "Merge develop into release" -b origin:release -h origin:develop
