name: Create Pull Request to Push Dev to Release

on:
  pull_request:
  push:
    branches:
    - develop
    - release

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Check out release
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: release
    - name: Reset release branch to base on develop
      run: |
        git checkout -b merge-develop-to-release
        git fetch origin develop:develop
        git reset --hard develop
    - name: Create Pull Request
      run: |
        git push -u origin merge-develop-to-release
